apiVersion: v1
kind: Secret
metadata:
  name: hangar-backend
  labels:
    {{- include "hangar.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.yaml: |
    spring:
      application:
        name: hangar-backend
      datasource:
        url: "jdbc:postgresql://{{ .Values.backend.config.postgresql.hostname }}:{{ .Values.backend.config.postgresql.port }}/{{ .Values.backend.config.postgresql.database }}{{ .Values.backend.config.postgresql.options }}"
        username: "{{ .Values.backend.config.postgresql.username }}"
        password: "{{ .Values.backend.config.postgresql.password }}"
    server:
      port: 8080
    management:
      server:
        port: 8081
      security:
        enabled: false
      endpoints:
        enabled-by-default: true
      endpoint:
        health:
          enabled: true
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
    fake-user:
      enabled: false

    hangar:
      dev: false
      base-url: "https://hangar.test"

      announcements:
        -
          text: "This is a staging server for testing purposes. Data could be deleted at any time. That said, signups are open, please test stuff and report and feedback on github or discord!"
          color: "#ff544b"

      sso:
        auth-url: "https://auth.hangar.test"
        oauth-url: "https://auth.hangar.test/hydra"
        client-id: "${SSO_CLIENT_ID}"
        api-key: "${SSO_API_KEY}"

      security:
        api:
          url: "https://auth.hangar.test"
          avatar-url: "https://auth.hangar.test/avatar/%s"
        token-secret: "${TOKEN_SECRET}"
        image-proxy-url: "https://auth.hangar.test/image/%s"

      storage:
        plugin-upload-dir: "/hangar/uploads"
        type: "local"
        access-key: "todo" # todo object storage creds
        secret-key: "todo"
        bucket: "todo"
        object-storage-endpoint: "http://localhost:9000"

    logging:
      level:
        root: INFO
        org.springframework: INFO
